uktrade/directory-constants

- directory_constants/constants/cms.py
- setup.py
[this task](https://uktrade.atlassian.net/browse/ED-4271)
> Add more CMS slugs

- directory_constants/constants/cms.py
- setup.py
[this task](https://uktrade.atlassian.net/browse/TT-833)
> Add soo success page slug

- directory_constants/constants/urls.py
- setup.py
https://uktrade.atlassian.net/browse/CMS-672
> Add new article categories to urls

- directory_constants/constants/urls.py
- setup.py
https://uktrade.atlassian.net/browse/CMS-902
> Add great international urls

- CHANGELOG.md
- setup.py
Quite a simple upgrade due to the app only making use of Django's settings module (which hasn't changed at all). The rest is pure python.
> [CMS-1507] Add support for Django 2 -> 2.2

- CHANGELOG.md
- directory_constants/urls.py
- setup.py
This [ticket](https://uktrade.atlassian.net/browse/CMS-1671)
> CMS-1671 avoid redundant redirect to page with trailing / 

- CHANGELOG.md
- directory_constants/choices.py
- setup.py
> Added company types

- CHANGELOG.md
- directory_constants/urls.py
- setup.py
> CI-405 Add URLs: (FAS)Contact us, (Int)About DIT, (Int)Contact us

- CHANGELOG.md
- directory_constants/slugs.py
- setup.py
> GTRANSFORM-368 add missing slug for accessibility

- CHANGELOG.md
- directory_constants/urls/international.py
- setup.py
> Added content into how we help urls

- setup.py
> Version change

- CHANGELOG.md
- directory_constants/choices.py
- directory_constants/helpers.py
- setup.py
- tests/test_choices.py
- tests/test_helpers.py
- Filtered out UAE territories from main COUNTRIES_AND_TERRITORIES.
- Added COUNTRIES_AND_SELECTED_TERRITORIES which is all the countries plus Hong Kong.
- Added COUNTRIES_EXCLUDING_GB_AND_SELECTED_TERRITORIES which is all countries except GB plus Hong kong.
> Updated countries and territories

- CHANGELOG.md
- setup.py
> security fix

- CHANGELOG.md
- directory_constants/choices.py
- setup.py
> GP2-519-turn-over-choices 

- CHANGELOG.md
- directory_constants/choices.py
- directory_constants/fixtures/countryorterritory.region.type.json
- directory_constants/helpers.py
- setup.py
- tests/test_helpers.py
> GP2-388_list_of_countries_with_regions

- CHANGELOG.md
- directory_constants/choices.py
- setup.py
> GP2-699-swamp-route-to-market-constants

- CHANGELOG.md
- directory_constants/choices.py
> gp2-849 - add target-age-group-choices

- CHANGELOG.md
- directory_constants/choices.py
- setup.py
> GP2-285-add-export-choices

- CHANGELOG.md
- directory_constants/choices.py
- setup.py
> add funding options

- CHANGELOG.md
- directory_constants/choices.py
- setup.py
> Gp2-1382-getting-paid-options

- CHANGELOG.md
- directory_constants/choices.py
- setup.py
> fix bad choices

- CHANGELOG.md
- setup.py
> Update django version requirement

- CHANGELOG.md
- directory_constants/urls/__init__.py
- directory_constants/urls/magna.py
- setup.py
- tests/test_urls.py
This changeset adds magna urls to directory-constants
> Added magna urls for directory-components

- CHANGELOG.md
- directory_constants/urls/magna.py
- setup.py
> Added international home and profile link for magna

- CHANGELOG.md
- directory_constants/urls/magna.py
- setup.py
> Contact URL magna update

- CHANGELOG.md
- directory_constants/urls/international.py
- setup.py
> Added international contact us URL

- CHANGELOG.md
- setup.py
> Security vulneribilities

- CHANGELOG.md
- setup.py
> GP2-3404-fix-header-links

- CHANGELOG.md
- setup.py
> django upgrade

- CHANGELOG.md
- setup.py
> Update Django to security-patched version 3.2.13

- CHANGELOG.md
- directory_constants/helpers.py
- setup.py
> Dependencies upgrade 

- setup.py
> django vulnerability patch v3.2.16

- CHANGELOG.md
- setup.py
> KLS-449 Update Django

- setup.py
> KLS-449 Update PyPi version

- CHANGELOG.md
- setup.py
> Upgrade django to version 4.0.10

- CHANGELOG.md
- setup.py
> Support for Django 4.1.9

- .circleci/config.yml
- CHANGELOG.md
- setup.py
> Bump support for Django 4.1.9

- setup.py
> Bump version of twine used

- CHANGELOG.md
- setup.py
> Bump Django to min 4.2.10
